name: Distributable

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-win:
    runs-on: windows-latest
  
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'gradle'

      - name: build distributable
        run: ./gradlew :desktopApp:createDistributable

      - name: distributable to zip
        run: Compress-Archive -Path "desktopApp/build/compose/binaries/main/app/*" -DestinationPath "macrochat-win.zip"

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: win-distributable
          path: macrochat-win.zip
